### PR TITLE
Use relative paths.

### PR DESCRIPTION
**Pull request by pelmato**
Hi, I was not able to make the demo work with my local webserver on http://localhost/toto (pointing to "build" dir) because of absolute path. Seems to work fine after I removed heading '/'. Not sure if it may break something elsewhere.

### CODE REVIEW

**Comment by fabrik42** [comment]
Hey, thanks you for the hint! I will test it this week and if everything is fine, I will merge it.

Cheers,

Christian

**Comment by fabrik42** [comment]
Hi, this changes work fine for me and I'm happy to merge it!

Thank you for your contribution and let me know if there is anything I can help you with!

Cheers,

Christian

**Comment by pelmato** [comment]
Thank you very much for your work. I'm trying to use ffwdme on my Firefox OS phone. Firefox OS has no routing application yet and I hope I can use ffwdme instead. The first results are promising, but it still needs a lot of work. But again, thank you for this great project!

**Comment by fabrik42** [comment]
Hey, this is a pretty cool idea! I thought about it myself, but never started anything. I'm very curious how this will turn out.

Let me know, if there is anything I can help you with!

**Pull request merged**
